/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cranfoj' at '7/18/16 1:09 PM' with Gradle 2.14
 *
 * @author cranfoj, @date 7/18/16 1:09 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
